Fix cURL options
Combodo/combodo-webhook-integration pull request #11
Opened 2022-10-24 08:34 UTC by Hipska

- Fix bug introduced by https://github.com/Combodo/combodo-webhook-integration/pull/7#issuecomment-1286873879
- Fix typo bug for setting CA cert file

2022-10-26 07:18 UTC, Molkobain commented
I'm not sure about the `CURLOPT_POST => !empty($payload)`, when using the `ActionWebhook`, you can set a payload in the corresponding field and choose the GET method. The payload will then be send as a query parameter.

Maybe something like this would be more explicit and easier to maintain, what do you think?

```
		// Prepare cURL options
		$aCURLOptions = array(
			CURLOPT_RETURNTRANSFER => true,
// Stop setting this options for all requests
//			CURLOPT_CUSTOMREQUEST => strtoupper($sMethod),
//			CURLOPT_POST => ($sMethod === 'post'),
			// Note: We pass headers as a cURL option to avoid  bug N°3267 in \utils::DoPostRequest()
			CURLOPT_HTTPHEADER => $aHeaders,
			CURLOPT_CONNECTTIMEOUT => $sConnectionTimeoutInSeconds,
			CURLOPT_POSTFIELDS => $payload,
		);

		switch ($sMethod) {
			case 'get':
				$aCURLOptions[CURLOPT_HTTPGET] = true;
				break;

			case 'post':
				$aCURLOptions[CURLOPT_POST] = true;
				break;

			case 'put':
// Not sure it is necessary, I don't have PUT request examples
				$aCURLOptions[CURLOPT_PUT] = true;
				break;

			default:
				$aCURLOptions[CURLOPT_CUSTOMREQUEST] = strtoupper($sMethod);
		}
```

2022-10-26 07:19 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +			$aCURLOptions[CURLOPT_SSLCERT] = $sCACertFile;
Nice catch

2022-10-26 07:39 UTC, Hipska commented
I will test your suggestion with CURLOPT_PUT, but I like the idea!

2022-10-26 07:55 UTC, Hipska commented
It doesn't work with `CURLOPT_PUT`, as the curl then expects `CURLOPT_INFILE` and `CURLOPT_INFILESIZE` to be set.

What do you think about always setting `CURLOPT_CUSTOMREQUEST` and set the `CURLOPT_POST` to `true` in the case of `post` and `put`?

Is this statement even true?
> you can set a payload in the corresponding field and choose the GET method. The payload will then be send as a query parameter.

2022-10-26 10:11 UTC, Molkobain commented
> What do you think about always setting `CURLOPT_CUSTOMREQUEST` and set the `CURLOPT_POST` to `true` in the case of `post` and `put`?

You think the `CURLOPT_HTTPGET` isn't appropriate for the GET method?
Ok for POST / PUT methods.

> Is this statement even true?
> 
> > you can set a payload in the corresponding field and choose the GET method. The payload will then be send as a query parameter.

I thought so, but debugging the calls of a GET action the payload isn't part of the query params as excepted.
That is a bug IMO as some third-parties might expect them to be part of the URI.

2022-10-26 10:20 UTC, Hipska commented
`CURLOPT_GET` is the default anyway, so no need to set this I guess?

> I thought so, but debugging the calls of a GET action the payload isn't part of the query params as excepted.
That is a bug IMO as some third-parties might expect them to be part of the URI.

That is not a bug and totally as expected. For this situation there is the new `path` field for ActionWebhook.

2022-10-26 12:15 UTC, Molkobain requested changes
This and then good to merge

2022-10-26 12:15 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +
```suggestion
		switch ($sMethod) {
			case 'post':
			case 'put':
				$aCURLOptions[CURLOPT_POST] = true;
				break;
		}

```

There is no further case yet, but it might avoid a bug when someone adds a new case in the future if they don't see the `break` needs to be added

2022-10-26 12:19 UTC, Molkobain approved these changes

2022-10-26 12:19 UTC, Molkobain commented
Set for technical review in 10 days

2022-11-02 15:11 UTC, Molkobain commented
Accepted during technical review.

@Hipska can you tell me which apps you tested this against? So I can argue during functional review next week.
Thanks

2022-11-08 16:31 UTC, Molkobain commented
Accepted during functional review.
Will be part of next extension release and iTop 3.1

2022-11-08 16:32 UTC, merged