:bug: Validate the prepared JSON instead of the input JSON
Combodo/combodo-webhook-integration pull request #12
Opened 2022-12-21 14:05 UTC by Hipska

The current implementation doesn't support the following input JSON:
```
{ "some_integer": $this->some_integer$ }
```
While this can produce valid JSON after prepare:
```json
{ "some_integer": 123 }
```

2022-12-21 14:49 UTC, Hipska commented
Updated..

Other modules might still use it.. Maybe add a `@deprecated` tag?

2022-12-22 08:37 UTC, piRGoif commented
> Updated..

Thanks, perfect !

> Other modules might still use it.. Maybe add a `@deprecated` tag?

I don't have any `ApplyParamsToArray` uses in my cloned repo, but you're right it is a protected method in `ActionWebhook`, parent class of all impl... so yes it would be far better to have it `@deprecated` than simply remove it.

What do you think @Molkobain ?

2022-12-23 09:48 UTC, Molkobain commented
For a moment I was afraid it was a regression introduced by #9, but it's not, it was already there 😁

> Other modules might still use it.. Maybe add a @deprecated tag?

Not sur it's relevant to deprecate it, it can be used by any custom webhook action as a utility method if they handle arrays. I would rather keep it.

2022-12-23 09:50 UTC, Molkobain commented
Regarding the fix itself, it sounds good.
I would just like you to add a unit test for that method please (I know, I did add any myself at the time, but we tend to ask for tests in PRs now)

2022-12-23 09:50 UTC, Molkobain requested changes
Fix is good.
Just missing a unit test.

2022-12-23 10:10 UTC, piRGoif commented
> I would just like you to add a unit test for that method please

Indeed you're right. This would allow to document the use case this PR is solving, and adds lots of other ones.

Thomas there are no PHPUnit class for now but you can mimic what was done in other modules ? If you need help just tell us.

2023-04-06 08:39 UTC, Hipska commented
Yes I need help, I also asked help to @etaloc already..

2023-09-05 15:13 UTC, piRGoif commented
The same development was done (greatly because of Hipska) in #17.
In consequence we are closing this PR.

2023-09-05 15:13 UTC, closed without merging