N°6647 Improve JSON validity check
Combodo/combodo-webhook-integration pull request #17
Opened 2023-08-09 16:11 UTC by piRGoif

- we were only accepting PHP arrays as valid decoded value
- the validity check was made before having placeholders replaced

Those are flaws we saw during the discussion that occurs in #16 thanks to Hipska !

In this PR are the modifications only related to this validation improvement.

2023-08-10 07:39 UTC, Hipska requested changes

2023-08-10 07:39 UTC, Hipska commented on src/Core/Notification/Action/_ActionWebhook.php
> +			throw new WebhookInvalidJsonValueException('Invalid JSON format', [
```suggestion
			throw new WebhookInvalidJsonValueException(json_last_error_msg(), [
```

2023-08-10 07:39 UTC, Hipska commented on tests/php-unit-tests/ActionWebhookTest.php
> +		];
Maybe also add a case where `this->value` is an integer for example?

2023-08-10 07:39 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
>  		return $sPreparedDataAsJson;
```suggestion
		return $sReplacedInput;
```

2023-08-10 07:39 UTC, Hipska commented on src/Core/Notification/Action/_ActionWebhook.php
> +	 * @param mixed $sJson
```suggestion
	 * @param string $sJson
```

2023-08-10 07:39 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
Input to the JsonDecode method should only be a string

2023-08-10 07:39 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'invalid array' => ['{foo:bar}', true],
```suggestion
			'simple array' => ['{"foo":"bar"}', false, ['foo' => 'bar']],
			'integer array' => ['{"foo":123}', false, ['foo' => 123]],
			'invalid array' => ['{foo:bar}', true],
```

2023-08-10 13:29 UTC, piRGoif commented on src/Core/Notification/Action/_ActionWebhook.php
> +			throw new WebhookInvalidJsonValueException('Invalid JSON format', [
The message should be a static string that can be searched in the logged file
The json_last_error_msg() can be logged as an additional data : done in a337fd6d

2023-08-10 13:34 UTC, piRGoif commented on tests/php-unit-tests/ActionWebhookTest.php
> +		];
Good idea ! Done in fd55c4b7

2023-08-10 13:35 UTC, piRGoif commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'invalid array' => ['{foo:bar}', true],
Good idea ! Done in 53e35b61

2023-08-10 13:41 UTC, piRGoif commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
Not sure to understand what you mean ? The _ActionWebhook::JsonDecodeWithError tested method can get anything as input ?

2023-08-10 13:42 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
See my other comment; it shouldn't. JSON is a string, not any other type

2023-08-10 13:42 UTC, piRGoif commented on src/Core/Notification/Action/_ActionWebhook.php
> +	 * @param mixed $sJson
true, false or null are valid JSON values

2023-08-10 13:45 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
>  		return $sPreparedDataAsJson;
Fixed in be4ed1d3

2023-08-11 16:22 UTC, piRGoif commented on src/Core/Notification/Action/_ActionWebhook.php
> +	 * @param mixed $sJson
Indeed
`json_decode(true)` is working but `false` or `null` aren't as demonstrated by _ActionWebhookTest::IsJsonValidProvider
I was worried the method should remain generic but it will : there are no context where the source json won't be a string.
Changed with a1330afa

2023-08-12 06:14 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
This test needs to be updated.

2023-09-04 10:11 UTC, Hipska commented
This PR is now basically doing the same as my PR #12

2023-09-05 13:53 UTC, Hipska commented
Mine was first..

2023-09-05 14:54 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		try{
Technical review : add comment to explain we are checking JSON validity

2023-09-05 15:13 UTC, piRGoif commented
> Mine was first..

Yes, but it lacked some tests :/ 
Anyway many thanks, you did the first step with your pr, and greatly contribute in this other pr !

2023-09-05 15:26 UTC, Hipska requested changes
Looks a bit better.

Maybe also update the `payload` of `$aLogContext` to the prepared JSON instead of the input JSON?

2023-09-05 15:26 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			$decodedJson = static::JsonDecodeWithError($sReplacedInput);
```suggestion
		// replacing placeholders...
		$sPreparedDataAsJson = $this->ApplyParamsToValue($aContextArgs, $sInputAsJson);

		// and now checking JSON validity !
		try{
			static::JsonDecodeWithError($sPreparedDataAsJson);
```

2023-09-05 15:26 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		return $sReplacedInput;
```suggestion
		return $sPreparedDataAsJson;
```

2023-09-05 15:30 UTC, Hipska commented
> Yes, but it lacked some tests :/ 
This PR also doesn't have tests for the changed method `ApplyParamsToJson`, so in that regards exactly the same as my PR.

Your PR indeed adds some tests, but only for the new methods introduced by this PR.

2023-09-05 15:31 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
Still needs to be updated, not resolved..

2023-09-06 14:18 UTC, piRGoif commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
Woops sorry ok understood : only strings as inputs.

2023-09-06 14:34 UTC, piRGoif commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
To make things clearer, I've pushed 1ead23b8

2023-09-06 14:34 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
Indeed. These 2 tests with Boolean as inputs don’t make any sense and should be removed.

2023-09-06 14:39 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
> To make things clearer, I've pushed [1ead23b](https://github.com/Combodo/combodo-webhook-integration/commit/1ead23b81f6b0b6a388258f6f09ab0d7a412a197)

That’s even more nonsense. JSON IS A STRING, nothing else. There’s no way the method will receive any other type as input.

All other methods in iTop expecting a string also don’t have such a check, right?

2023-09-06 15:41 UTC, piRGoif commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
This is a public method in a class that should be extended for other hooks types. Any consumer can call this method with any data, including wrong types (because of a type conversion, because the input is read from somewhere else and we get an invalid value, etc etc).
We cannot have a type hinting in the method signature itself because of mandatory compatibility with iTop 2.7, so having the type check will ensure we won't have inconsistent behavior for inconsistent data.
It shouldn't happen, we are not used to have such checks, but it is here, why not keep it ?

2023-09-07 06:56 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			$decodedJson = static::JsonDecodeWithError($sReplacedInput);
Indeed, $decodedJson isn't used anywhere and $sReplacedInput isn't the clearer name
I'll go more for something like $sJsonWithReplacedPlaceholders ?
Pushed with f3439956

2023-09-07 06:56 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		return $sReplacedInput;
Will be handled with conversation above

2023-09-07 07:33 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
Because of 
> we are not used to have such checks

So why make an exception to that here?

2023-09-07 07:35 UTC, Hipska requested changes
Some changes seems to not have come through..

Also, there are no tests for `ApplyParamsToJson` method.

2023-09-07 07:35 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		return $sJsonWithReplacedPlaceholders;
```suggestion
		return $sPreparedDataAsJson;
```

2023-09-12 15:00 UTC, piRGoif commented
Functional review OK for 3.1.1

2023-09-13 10:21 UTC, piRGoif commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
Accepted during review

2023-09-13 12:12 UTC, Hipska commented on tests/php-unit-tests/_ActionWebhookTest.php
> +			'true' => [true, false, 1],
What do you mean with that?

2023-09-19 08:47 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$sJsonWithReplacedPlaceholders = $this->ApplyParamsToValue($aContextArgs, $sInputAsJson);
Hello,
Can you explain the reasons why you're suggesting this new naming ?

2023-09-19 08:47 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			static::JsonDecodeWithError($sJsonWithReplacedPlaceholders);
Closing conversation, duplicate

2023-09-19 08:47 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		return $sJsonWithReplacedPlaceholders;
Closing conversation, duplicate

2023-09-19 08:48 UTC, piRGoif commented
> Some changes seems to not have come through..

@Hipska what do you mean ? 

> Also, there are no tests for ApplyParamsToJson method.

Good enough for the review

2023-09-19 08:49 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$sJsonWithReplacedPlaceholders = $this->ApplyParamsToValue($aContextArgs, $sInputAsJson);
It's not new naming, it is the original naming so the return statement is not changed with this PR..

2023-09-19 08:54 UTC, Hipska commented
> > Some changes seems to not have come through..
> 
> @Hipska what do you mean ?

I suggested changes, but some of them weren't incorporated, so with that review I suggested them again.

> > Also, there are no tests for ApplyParamsToJson method.
> 
> Good enough for the review

But my PR was closed because of the same reasons?

See my other comment:
> This PR also doesn't have tests for the changed method ApplyParamsToJson, so in that regards exactly the same as my PR.

2023-09-19 08:56 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		return $sJsonWithReplacedPlaceholders;
You can see here that it was the original return value naming..

2023-09-19 08:56 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$sJsonWithReplacedPlaceholders = $this->ApplyParamsToValue($aContextArgs, $sInputAsJson);
From a consumer point of view, the ApplyParamsToJson method still returns a string, still with the same content.
What is the point of keeping the name of a method internal var ? 
As we changed the method works internally, renaming improves code readability.

2023-09-20 16:30 UTC, merged

2023-09-20 17:02 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +		$sJsonWithReplacedPlaceholders = $this->ApplyParamsToValue($aContextArgs, $sInputAsJson);
+1 about the name suggested by Thomas

2023-09-20 21:05 UTC, Hipska commented
👎