Allow for mentioning new user IDs in slack messages
Combodo/combodo-webhook-integration pull request #18
Opened 2023-08-17 15:14 UTC by peckpeck

To mention a user in a Slack message, you should write in Markdown "... <@userID> ..."

However, for original user ID it also supports the HTML form "... &lt;@userID&gt; ...", but this doesn't work with new user IDs of the form UXXXX (they can be found in the user profile).

iTop webhooks store messages in HTML and convert them to Markdown, but it doesn't transform the UID syntax, so mentioning user for old users works, but not for recent users.

This patch makes the translation to fix this behavior.

2023-09-25 13:46 UTC, peckpeck commented
Hi,
How can we help on this issue ?

2023-09-25 16:39 UTC, Molkobain commented
Hello @peckpeck ,

Community PRs are reviewed once a month by the technical and functional teams. We couldn't review this one last month, but it should be done next week hopefully. I'll let you know.

2023-11-21 13:35 UTC, peckpeck commented
@Molkobain any news on this one ?

I see that there is a conflict, what should be my target branch ?

2024-01-04 13:28 UTC, peckpeck commented
Hi, is there anything I can do to help making progress on this one ?

2024-01-04 16:45 UTC, Hipska commented
Resolve the conflicts would indeed already help. You could try to contact them on our Slack space.

2024-01-05 10:42 UTC, Molkobain commented
Hello @peckpeck ,

Sorry, the only think blocking this is our lack of time to handle PRs. :/

I'm checking it now, could you give us examples of how it should look in HTML and Markdown for both old and new user IDs?
This way, I'll be able to test and add a unit test on that.

Thanks

2024-01-05 11:21 UTC, peckpeck commented
Sorry to hear that, thank you for you work.

For tests : 
- iTop stores messages as html so `hello <@name>` is stored as `hello &lt;@name&gt;`
- in slack API, a very little subset of html is allowed inside the markdown message
- old slack UIDs are equal to the user name, new slack UIDs are of the form Uxxxxxx (with x a digit)

With old UIDs : 
- this works `hello <@uid>`
- this works `hello &lt;@uid&gt;` but is deprecated

With new UIDs :
- this works `hello <@Uxxx>`
- this doesn't work `hello &lt;@Uxxx&gt;`

2024-01-05 11:22 UTC, peckpeck commented on datamodel.combodo-webhook-integration.xml
> +		$sContent = preg_replace('/&lt;([!@].*?)&gt;/', '<$1>', $sContent);
the `!` is used when sending a message to a group

2024-01-05 13:29 UTC, Molkobain commented
> With new UIDs :
> 
> [...]
> * this doesn't work `hello &lt;@Uxxx&gt;`

Doesn't work in Slack at all or doesn't work with the current webhook module?
I'll test this later this afternoon.

2024-01-05 13:32 UTC, peckpeck commented
`hello &lt;@Uxxx&gt;` is what the current module produces when you try to write `hello <@uid>` in the message parameter, and it doesn't work with slack at all.

2024-01-10 09:38 UTC, Molkobain commented
So, I was testing the PR and there are still a few points to clear out.

  * What is the synthax to mention a group, is it `<!C123ABC>` or `<!@C123ABC>`, I wasn't able to find the documentation
  * When you say "message to a group", do you mean this kind of group fo several people?
    ![image](https://github.com/Combodo/combodo-webhook-integration/assets/5130468/2f6d4b7c-339d-4b76-af00-98c6a4712e6e)
  * I started a unit test for the transformation from HTML to Slack markup, do you confirm these test cases?
    With the current implementation not all cases pass.

| HTML from iTop | Slack markup to send | Passing test |
| ------------------ | ----------------------- |---------------|
| `<@Molkobain>` | `<@Molkobain>` | ❌ |
| `&lt;@Molkobain&gt;` | `<@Molkobain>` | ✔️ |
| `<@U123456ABC>` | `<@U123456ABC>` | ❌ |
| `&lt;@U123456ABC&gt;` | `<@U123456ABC>` | ❌ |
| `<!@SomeGroup>` | `<!@SomeGroup>` | ❌ |
| `&lt;!@SomeGroup&gt;` | `<!@SomeGroup>` | ✔️ |

  * Rebase it on the support/1.3 branch? Branch has been created these days as there will be a breaking change for iTop 3.2+
    You need to make a `rebase onto`, if you are not familiar with the operation, we can do it and push on your repo, but it seems like your branch is protected.

2024-01-10 10:13 UTC, peckpeck commented
What I see in your screenshot looks more like a private conversation than a group. To create a user group, go to your workspace settings (you probably need to be an admin) and you have a "User group" menu entry.

Group mention should be `<!SomeGroup>`
I don't really use group mentions with itop, but I took the information from this documentation https://api.slack.com/reference/surfaces/formatting

I don't really understand your test cases because line 1,3,5 are not possible to generate with the iTop interface.

I don't understand the meaning of the 3rd column, does it mean that a working content is sent (which seems to be the case since the line 2 is checked) ? Or does it mean that it sends the expected format (which would be the reason for the presence of 2nd column) ? in which case line 2 should not be checked

2024-01-10 10:24 UTC, peckpeck commented
Hi, I rebased the branch, but should I change the PR target too ?

2024-01-10 19:51 UTC, Molkobain commented
> Hi, I rebased the branch, but should I change the PR target too ?

Thanks! Yes the target branch must be changed in the PR as well, I just did it. :)

2024-01-10 19:58 UTC, Molkobain commented
Thanks for all the info!

> What I see in your screenshot looks more like a private conversation than a group. To create a user group, go to your workspace settings (you probably need to be an admin) and you have a "User group" menu entry.
> 
> Group mention should be `<!SomeGroup>` I don't really use group mentions with itop, but I took the information from this documentation https://api.slack.com/reference/surfaces/formatting

We don't use Slack internally, we just have a free dev instance to test the webhooks. I found the option, but it's for paid plans, so I won't be able to test it. But from the documentation you pointed, it matches with your proposal.

> I don't really understand your test cases because line 1,3,5 are not possible to generate with the iTop interface.

They can be done programmatically. One can prepare and send webhooks from a script, it's not only from the notifications only. But after taking a look at the method again, even then we can't use `<>` as they will be remove by the `strip_tags()` call, so I removed the test cases.

> I don't understand the meaning of the 3rd column, does it mean that a working content is sent (which seems to be the case since the line 2 is checked) ? Or does it mean that it sends the expected format (which would be the reason for the presence of 2nd column) ? in which case line 2 should not be checked

It means that the output is the markup expected by Slack and that it appears as expected in Slack.

Can you add the following unit test to your PR?
**File** combodo-webhook-integration/tests/php-unit-tests/ActionSlackNotificationTest.php
**Content**
```php
<?php
/*
 * @copyright   Copyright (C) 2010-2023 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

namespace Combodo\iTop\Test\UnitTest\CombodoWebhookIntegration;

use ActionSlackNotification;
use Combodo\iTop\Test\UnitTest\ItopDataTestCase;


class ActionSlackNotificationTest extends ItopDataTestCase
{
	/**
	 * @dataProvider TransformHTMLToSlackMarkupProvider
	 *
	 * @param string $sInput
	 * @param string $sExpected
	 *
	 * @return void
	 */
	public function testTransformHTMLToSlackMarkup(string $sInput, string $sExpected): void
	{
		$sTested = ActionSlackNotification::TransformHTMLToSlackMarkup($sInput);
		$this->assertEquals($sExpected, $sTested, "HTML not transform to Slack Markup as expected");
	}

	public function TransformHTMLToSlackMarkupProvider(): array
	{
		return [
			"Hyperlink" => [
				"input" => <<<HTML
<a href="https://github.com/Combodo/iTop" _target="blank">iTop Repository</a>
HTML,
				"expected" => "<https://github.com/Combodo/iTop|iTop Repository>",
			],
			"Mention old user ID with special chars encoded" => [
				"input" => <<<HTML
&lt;@Molkobain&gt;
HTML,
				"expected" => "<@Molkobain>",
			],
			"Mention new user ID with special chars encoded" => [
				"input" => <<<HTML
&lt;@U123456ABC&gt;
HTML,
				"expected" => "<@U123456ABC>",
			],
			"Mention new group ID with special chars encoded" => [
				"input" => <<<HTML
&lt;!SomeGroup&gt;
HTML,
				"expected" => "<!SomeGroup>",
			],
		];
	}
}

```

2024-01-10 19:59 UTC, Molkobain requested changes

2024-01-10 19:59 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +		// Replace user Ids
```suggestion
		// Replace users and groups IDs to ensure they don't have HTML entities
		// Note: As an input, only HTML entities IDs (eg. "&lt;@U123ABC&gt;") are supported as raw IDs (eg. "<@U123ABC>") will be considered unexpected tags and be removed by the `strip_tags()` above.
```

2024-01-11 09:58 UTC, Hipska approved these changes

2024-01-23 14:23 UTC, peckpeck commented
Done, sorry for the delay

2024-01-23 16:11 UTC, Molkobain approved these changes

2024-01-23 16:11 UTC, Molkobain commented
Great thanks, PR will be reviewed by the team on february second tuesday.

2024-02-14 09:22 UTC, Molkobain commented
Accepted during functional review

2024-02-14 09:22 UTC, merged