Hungarian translations
Combodo/combodo-webhook-integration pull request #19
Opened 2023-12-12 11:06 UTC by piRGoif

Done by @tacsaby

Translations on iTop were pushed with Combodo/iTop#584

2023-12-12 11:35 UTC, Hipska requested changes

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> + * @copyright   Copyright (C) 2017 ITOMIG GmbH
This isn't right

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> -	'Class:ActionWebhook/Attribute:path+' => 'Additional path to append to the connection URL (eg. \'/some/specific-endpoint\')~~',
Please revert, the one for `Value:head` can be `HEAD`.

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```suggestion
- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \\SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $oResponse, $oAction)
```suggestion
- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \\SomeClass::XXX($oObject, $oResponse, $oAction)
```

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```suggestion
- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \\SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```suggestion
- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \\SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```suggestion
- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \\SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +	'ActionRocketChatNotification:additionalelements' => 'Bot információ'
```suggestion
	'ActionRocketChatNotification:additionalelements' => 'Bot információ',
```

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```suggestion
- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \\SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```

2023-12-12 11:35 UTC, Hipska commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```suggestion
- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \\SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
```

2023-12-12 16:31 UTC, Molkobain commented
Accepted during functional review

2023-12-13 08:23 UTC, Molkobain requested changes
Nothing more than HIpska, he pointed it all out 😁

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> + * @copyright   Copyright (C) 2017 ITOMIG GmbH
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> -	'Class:ActionWebhook/Attribute:path+' => 'Additional path to append to the connection URL (eg. \'/some/specific-endpoint\')~~',
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $oResponse, $oAction)
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +	'ActionRocketChatNotification:additionalelements' => 'Bot információ'
Fixed in d824e455

2023-12-20 11:38 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
Fixed in d824e455

2023-12-20 11:39 UTC, piRGoif commented on hu.dict.combodo-webhook-integration.php
> +- Bármely PHP osztályból, statikusnak ÉS nyilvánosnak kell lennie. A névnek teljesen minősített névnek kell lennie. Példa: \SomeClass::XXX($oObject, $aContextArgs, $oLog, $oAction)
Fixed in d824e455

2023-12-20 15:15 UTC, piRGoif commented
About \SomeClass VS \\SomeClass : what I see in the UI is the following

![image](https://github.com/Combodo/combodo-webhook-integration/assets/8947448/b37312a1-c2ef-420b-888a-50e14195fc56)

I will replace all values to remove the backslash :)

2023-12-20 15:33 UTC, piRGoif commented
Wooops after a chat with Guillaume, revert modification so that `\SomeClass::...` would appear anywhere
The goal is to make visible it is a FQCN that should be set

2023-12-20 15:37 UTC, merged