N°8008 - Webhooks: Failed to update triggering object on process response callback
Combodo/combodo-webhook-integration pull request #22
Opened 2024-11-29 15:50 UTC by accognet

If the webhook is in synchronous mode
The callback method should not call BDUpdate(). The update is done at the end of the whole process.

2024-11-29 16:13 UTC, Hipska approved these changes

2024-12-02 11:57 UTC, Molkobain requested changes

2024-12-02 11:57 UTC, Molkobain commented on src/Core/Notification/Action/_ActionWebhook.php
> +                    $aHandlerParams['oObject'] = $oTriggeringObject;
```suggestion
                    $aHandlerParams['oTriggeringObject'] = $oTriggeringObject;
```

Oversight on my end

2024-12-02 15:30 UTC, eespie approved these changes

2024-12-03 13:04 UTC, odain-cbd requested changes
please provide some tests on top of this fix before merging

2024-12-20 08:15 UTC, Molkobain approved these changes

2024-12-20 09:40 UTC, odain-cbd commented on tests/php-unit-tests/ActionWebhookTest.php
> +	public function WhenObjectIsUpdated(DBObject $oDBObject)
I'd rename the function. to let know which field is updated. callback could not work and the test could pass if this function does below action
$oDBObject->Set('name', 'NameByCallBack');

2024-12-20 09:41 UTC, odain-cbd commented on tests/php-unit-tests/ActionWebhookTest.php
> +	public function WhenObjectIsCreated(DBObject $oDBObject)
same. i'd rename the function

2024-12-20 09:41 UTC, odain-cbd commented on tests/php-unit-tests/ActionWebhookTest.php
> +			'url' => 'http://localhost',
this test will make a remote call to this URL... maybe we should mock this call.

2024-12-23 11:11 UTC, merged

2025-04-24 10:48 UTC, Hipska commented
Please be aware that the PHPDoc of ExecuteResponseHandler isn't correct anymore because of this change.