N°5472 Check JSON payload in CheckToWrite
Combodo/combodo-webhook-integration pull request #8
Opened 2022-08-31 08:35 UTC by piRGoif

Since N°4753 and version 1.1.0 the JSON payload validity are checked when the action is processed (ActionWebhook::ApplyParamsToJson)

This is usefull, but the action author is warned at the very last moment that he made a mistake in its JSON value...

This PR adds a DoCheckToWrite method that checks JSON validity.

2022-08-31 12:06 UTC, Molkobain commented on en.dict.combodo-webhook-integration.php
> +	'Class:ActionWebhook:Error:payload:InvalidJson' => 'Warning : the payload field contains an invalid JSON value, the action won\'t be processed',
```suggestion
	'Class:ActionWebhook:Error:payload:InvalidJson' => 'Warning: The payload field contains an invalid JSON value, the action won\'t be processed',
```

2022-08-31 12:07 UTC, Molkobain commented on fr.dict.combodo-webhook-integration.php
> +	'Class:ActionWebhook:Error:payload:InvalidJson' => 'Attention : le champ Charge Utile contient un JSON invalid, l\'action ne pourra pas être exécutée',
```suggestion
	'Class:ActionWebhook:Error:payload:InvalidJson' => 'Attention : Le champ Charge Utile contient un JSON invalid, l\'action ne pourra pas être exécutée',
```

2022-08-31 12:09 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +		if (get_class($this) !== ActionWebhook::class) {
The ActioniTopWebhook could also be using the check, we should discuss about this.

2022-08-31 12:14 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs)
Why did you remove the `$oLog` parameter? It is passed by the calling method (`PrepareWebRequest`). The idea is that derived classes can manipulated the log if necessary.

2022-08-31 12:27 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs)
Oooook !
The parameter wasn't used in any existing implementation and there was no PHPDoc documenting the phpdoc so...
I'll restore it and document it could be null.

2022-08-31 12:29 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		if (get_class($this) !== ActionWebhook::class) {
A simple solution would be to do the check only if the payload field was editable by the user ? 
Another would be to check for modified fields, but I'd rather not as for bad JSON displaying a warning on each object modification (even if the payload field itself wasn't modified) is a must I think ?

2022-08-31 13:07 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs)
Done in 88b7c42d
Warning there are conterparts : removing the type hinting in the method signature and remove the reference sign.

2022-08-31 14:05 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Won't changing the argument type hint have an impact on child classes?

2022-08-31 14:45 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +		if (get_class($this) !== ActionWebhook::class) {
Not sure, I need to think about this.

2022-09-01 07:18 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		if (get_class($this) !== ActionWebhook::class) {
Another way would be to have a ShouldCheckJsonOnCheckToWrite returning a boolean, and implement as needed in the child classes ?

2022-09-05 15:09 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Yes it will : 

> Covariance allows a child's method to return a more specific type than the return type of its parent's method. Whereas, contravariance allows a parameter type to be less specific in a child method, than that of its parent. 
https://www.php.net/manual/en/language.oop5.variance.php

But we need the second parameter to be nullable !

We had the same problem with \CMDBObject::SetCurrentChange... Having types in method signatures is tricky...

Currently there is only one override in \ActioniTopWebhook

2022-09-12 08:42 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
> Currently there is only one override in \ActioniTopWebhook

In this module, but there are already several classes extending the base class in third-party extensions

2022-10-18 12:31 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		if (get_class($this) !== ActionWebhook::class) {
Discussed with Guillaume : we could have a validation service but this would be overkill...
As a compromise I will extract the JSON validation to a dedicated method so that any child class needing this check can call it directly !

2022-10-18 12:33 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Discussed with Guillaume : I will change GetContentType so that it gets called with the headers array. Indeed in DoCheckToWrite we won't be able to replace placeholders so we will get headers values from the attribute itself.
That means we will keep the original call to PrepareHeaders and won't call it anymore in GetContentType, and in consequence we won't need to change its signature.

2022-10-21 11:48 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
If it can be null, shouldn't it just be like this?
```suggestion
					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, ?EventNotification $oLog)
```

2022-10-21 12:00 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Module must remain compatible with iTop 2.7.0, meaning PHP 5.6 min. Otherwise we would have keep the type hint yes :/

2022-10-21 12:08 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Oh, didn't keep that in mind. But isn't the null value already possible because originally  it was `&$oLog`?

2022-10-21 13:52 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Actually I think it triggered an exception when the param was null. That's why we went that way, but Pierre will confirm or not.

2022-10-21 14:12 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
I can't recall precisely sorry :/ But yeah it was for sure blocking, and we had the exact same problem in other methods in the past... Adding type hinting in method signature isn't so easy...

2022-10-21 14:46 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Seems like it should be like this then:
```suggestion
					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, EventNotification $oLog = null)
```

Proof: https://3v4l.org/XHWQm

2022-10-21 15:11 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
But then you can't pass the $oLog as a reference like done in other Action classes, it will fail.

2022-10-21 15:18 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
1. it's an object, so those are always passed as reference
2. it will not fail for the supported php versions: https://3v4l.org/hGv7O

2022-10-21 15:20 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
Objects are always passed by reference, right ? 
But anyway I'm working on it, I will submit in some minutes the solution we discussed with Guillaume which rolls back the signature modification.

In case you want to dig further, the links to the PHP documentation are in the method PHPDoc block :o)

2022-10-21 15:26 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
We should ensure that the param is never passed as null, otherwise it still fails: https://3v4l.org/qmiNS
But anyway I think that part of the code isn't changed anymore right?

2022-10-21 15:26 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +					<code><![CDATA[	protected function PrepareHeaders(array $aContextArgs, $oLog)
I've just pushed the refactoring to get rid of the signature modification.
Closing this conversation !

2022-10-21 15:43 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		if (get_class($this) !== ActionWebhook::class) {
Done ! Closing conversation

2022-10-21 15:45 UTC, piRGoif commented
Refactoring designed with Guillaume done ! 
The PR is ready for review \o/

2022-10-21 15:58 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
Actually shouldn't this whole function just do apply the params and then validate the JSON?


This input JSON is currently not possible:
```
{ "some_integer": $this->some_integer$ }
```

While the resulting JSON will be perfectly valid.

2022-12-21 09:52 UTC, piRGoif commented
rebase & force push

2022-12-21 10:24 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
@piRGoif ?

2022-12-21 10:24 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		return $aJsonStructure;
Actually I've just picked the existing code...
You suggestion seems like a good idea ! Note that in the other PR where we try to log the error (#9), the `json_last_error` function was always returning the same value and wasn't very helpful...
Done in 6ecb40de

2022-12-21 10:24 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
In the DoCheckToWrite context we are unable to apply params...

2022-12-21 10:26 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
So, what about my comment? The provided JSON will not be able to be saved.

A warning message after saving instead of preventing to save would be better I guess..

2022-12-21 10:32 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
The check is non blocking : see in DoCheckPayload, in case of error we are adding an entry in m_aCheckWarnings instead of $m_aCheckIssues.

2022-12-21 10:35 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
Okay, that is fine. Didn't place a comment over there.

This ApplyParamsToJson will first validate the JSON and only then apply the paramaters. Where in my example would never be accepted as valid JSON as it will only become valid after applying the parameters.

2022-12-21 10:55 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
Yes, you're perfectly right.
The behavior was the same before...
Your example should be ok after adding double quotes around the parameter ?

2022-12-21 11:03 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
Indeed, didn't work before as well.

No, then the field is no longer a JSON integer, but a string. The API endpoint throws errors on that..

2022-12-21 13:09 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
I was suspicious about the validity of having integer without double quotes as values, but seems like json_decode [is ok with that](https://3v4l.org/7KUCO)
I'm closing the conversation as it is out of scope of this pr, anyone interesting in fixing the bug can submit another pr.

2022-12-21 13:31 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
Of course as this is correct [JSON syntax](https://www.json.org/json-en.html).  I was hoping this could be solved by this PR while it is a small fix and you were touching the relevant parts..

2022-12-21 13:36 UTC, Hipska approved these changes

2022-12-21 13:45 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
I opened this PR almost 4 months ago, I prefer to keep only one subject and don't change any other behaviors.

2022-12-21 13:49 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
I gave this as review comment the day you marked it ready for review 😉

2022-12-21 13:57 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
Sorry I'm answering just now :/ This PR had a long story :D

2022-12-21 14:01 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +	 * @return boolean|array<string, string> false if the JSON can't be deserialized, otherwise the deserialized structure
```suggestion
	 * @return boolean|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
```
Actually, `false` or even `"foobar"` is also a valid JSON..

2022-12-21 14:05 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		$aInputAsArray = $this->ValidateJsonString($sInputAsJson);
No worries, created the PR: https://github.com/Combodo/combodo-webhook-integration/pull/12

2023-04-04 13:57 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +	 * @return boolean|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
```suggestion
	 * @return bool|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
```

2023-04-04 18:11 UTC, Molkobain commented on datamodel.combodo-webhook-integration.xml
> +	 * @return boolean|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
Because we put bool everywhere, so it was to keep the consistency.

2023-04-06 07:58 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +	 * @return boolean|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
OK
I had a vague memory about a problem when using either bool or boolean in a method signature (in code, not just in phpdoc). Turns out it is boolean that [causes a problem](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.base.scalar), and [bool is the right type name in PHP](https://www.php.net/manual/en/language.types.type-system.php).
So indeed we should always use bool and never boolean !

2023-04-20 09:23 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +	 * @return boolean|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
I've just document this : https://www.itophub.io/wiki/page?id=latest:customization:coding_standards#bool_vs_boolean

2023-04-20 09:52 UTC, Hipska requested changes

2023-04-20 09:52 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			}
We had similar discussion before, but this new check us useless to perform on the raw unprepared payload because of the placeholders.

2023-04-20 09:52 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +	 * @return bool|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
A JSON decode could result in anything:
```suggestion
	 * @return bool|mixed false if the JSON can't be deserialized, otherwise the deserialized structure
```

Also, what if the original JSON would be just `false` or `null`? I think the only way to check for decode errors is to throw an exception.

2023-04-21 15:14 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
Yes we did :) The consensus was to keep the message but only as a non blocking warning.
We had the discussion also during at least one functional review.
To mitigate we could modify the dict entry, or check if the string contains placeholders (but I'm not very found of this idea :/ )
Do you have anything to propose ?

2023-04-21 15:23 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +	 * @return bool|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
`json_decode()` is called with its second parameter $associative set to true. Do you have examples of a value returning other thing that what I wrote in the phpdoc block ? 

If the original value is the string "false", ValidateJsonString will return false... as an error would. I'll add a test to return true in such case meaning : no json_decode error, but we cannot return an array).

The null value shouldn't happen as we are getting the value from a string field ? Did you have any use case in mind ? Plus the phpdoc says string and not ?string (this is just an information though and not in the PHP method signature)

2023-04-21 15:25 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +	 * @return bool|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
Handling "false" input : b38a6efc

2023-04-28 08:29 UTC, piRGoif commented
rebase & force push

2023-04-28 08:36 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
Just pushed a dict key modification, but I fear the message will be too long and hard to understand while most people aren't using placeholders... 
Will be discussed during reviews.

2023-04-28 09:42 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			}
The new text is indeed a bit long and could be simplified.

2023-04-28 09:44 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
I'm open to suggestions :)

2023-04-28 10:01 UTC, Hipska requested changes

2023-04-28 10:59 UTC, Hipska requested changes

2023-04-28 10:59 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			}
This check does not make sense. As already outlined not all (valid) JSON strings result in a php array.

2023-04-28 10:59 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +		if (false === $aInputAsArray) {
Same remark here, the code will now complain about invalid JSON even when the input is valid.

2023-04-28 12:18 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +	 * @return bool|array<string, mixed> false if the JSON can't be deserialized, otherwise the deserialized structure
Closing clonversation as I pushed a new approach and you already commented on it

2023-04-28 12:21 UTC, piRGoif commented on en.dict.combodo-webhook-integration.php
> +	'Class:ActionWebhook:Error:payload:InvalidJson' => 'Warning: The payload field contains an invalid JSON value (control done without replacing placeholders). Action can\'t be processed with invalid J
Thanks, nice and simple ! Commited in eddc2c8d (modified both EN and FR dict)

2023-04-28 12:31 UTC, piRGoif commented
Thanks for your latest comments @Hipska 
Working on it, switching to draft in the meantime.

2023-04-28 13:29 UTC, piRGoif commented
Using Hipska test cases, I rewrote it a little : https://3v4l.org/8dV8c#v8.0.28

2023-05-02 08:47 UTC, Hipska approved these changes
This looks much better now.

2023-05-02 08:47 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			}
Still open suggestion.

2023-05-02 08:47 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
>  		return $sPreparedDataAsJson;
Why not simply return `$sReplacedInput`?

2023-05-02 08:49 UTC, piRGoif commented
Should be OK now.

2023-05-02 08:50 UTC, Hipska commented
Just did a review..

2023-05-02 08:51 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +				</method>
See my latest commits :)
Closing this conversation, you might open new on the current code base.

2023-05-02 08:51 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +		if (false === $aInputAsArray) {
Closing as there are new commits intend to fix this

2023-05-02 08:55 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
>  		return $sPreparedDataAsJson;
Didn't changed the method way of doing things. 
The json_decode/json_encode might not be necessary... What do you think @Molkobain ?

2023-05-02 09:01 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
That would mean the method could return "" as null right ? Not very found of this idea :/

2023-05-02 09:04 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			}
It will only return if matches. The `+` in the regex makes sure it doesn't match an empty string..

2023-05-02 10:16 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
Added a PHPUnit test in 59770faa, and fix possible undefined index notices in e06e32b4
When removing the length test, the 2 last dataprovider case are failing : Failed asserting that '' is identical to null

2023-05-02 10:43 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			}
Please note that I also suggested a different RegEx, with that the tests should al succeed.

2023-05-02 11:32 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
Woops, my apologies.
After copying / pasting your whole code block, I got the last dataprovider case ("header value only spaces and tab") that is failing for the same reason.

2023-05-02 13:59 UTC, Molkobain approved these changes

2023-05-02 14:32 UTC, Hipska commented on datamodel.combodo-webhook-integration.xml
> +			}
Okay, didn't know such cases ever happen..

2023-05-02 15:25 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
Didn't achieve to make it work :(
So keeping the code as is :/

2023-05-04 09:02 UTC, piRGoif commented on datamodel.combodo-webhook-integration.xml
> +			}
After some chat with @odain-cbd we managed to make it work \o/
See 3bf5dc03

2023-05-04 09:07 UTC, Hipska approved these changes

2023-07-31 09:46 UTC, piRGoif commented
The merge of PR #13 make my work almost impossible to rebase :( Closing this PR.
I'm trying to cherry pick the changes manually, if I succeed without spending to much time I'll reopen a new PR.

2023-07-31 09:46 UTC, closed without merging